### ISSUE TITLE
Make sure to retry when GitHub issue import API call fails if it's not considered yet

### ISSUE THREAD

**Issue by mocobeta** [vlsi/bugzilla2github#10]
Hi, 
I just wanted to share my experience on https://github.com/apache/lucene-jira-archive. 

When I ran full import for 10600+ Lucene issues to GitHub via https://gist.github.com/jonmagic/5282384165e0f86ef105 several times, I occasionally encountered 5XX server errors. According to my trials, 5XX errors can occur with a probability of ~0.1%.

I skimmed through the `.kt` files but couldn't determine whether the retry code is already implemented or not; please close this issue if it is already considered.

**Comment by vlsi** [comment]
I rely on sequential import order (I have no "patch issue links" pass), and I would like to refrain from importing the same issue multiple times.

So my plan is to stop processing on API failure and let the user decide what to do next.

**Comment by mocobeta** [comment]
Ah okay, stop-on-a-failure is a strategy. 
I think it'd be better to let the infra team know that one or two failures could happen due to GitHub's outage during importing, depending on the total number of issues. If the total number is small (~1000), this would practically not be a problem.
