### ISSUE TITLE
Recognize and convert direct bugzilla URLs to issue references

### ISSUE THREAD

**Issue by vlsi** [vlsi/bugzilla2github#7]
See
* https://github.com/vlsi/tmp-jmeter-issues/issues/1154#issuecomment-1204129242
* https://bz.apache.org/bugzilla//show_bug.cgi?id=41921#c18

**Comment by mawasak** [comment]
Similar issue    ( https://github.com/vlsi/tmp-jmeter-issues/issues/1188#issuecomment-1204131301 ) but address is issues.apache.org
